name: Check Repo Branch for changes

on:
  workflow_call:
    inputs:
      branch:
        required: true
        type: string
      # path:
      #   required: true
      #   type: string
    secrets:
      pat_token:
        required: true

jobs:
  
  CheckoutWorkflows:
    runs-on: ubuntu-latest
    steps:
      
      - name: Checkout eg_sfcc
        uses: actions/checkout@v3
        with:
          repository: ShopEmpowerGlobal/eg_sfcc
          ref: ${{ inputs.branch }}
          token: ${{ secrets.pat_token }}
          # path: ${{ inputs.path }}
          fetch-depth: 0

      # - name: Get changed files
      #   id: changed-files
      #   uses: tj-actions/changed-files@v34


      - name: List all changed files
        run: |
          for file in ${{ steps.changed-files.outputs.all_changed_files }}; do
            echo "$file was changed"
          done
      
      - name: Check for new commits today
        id: check-new-commits
        uses: adriangl/check-new-commits-action@v1
        with:
          token: ${{ secrets.pat_token }}
          seconds: 86400 # One day in seconds
          branch: ${{ inputs.branch }}
          # working-directory: ${{ inputs.path }}
      
      - name: Print something if new commits are found
        if: ${{ steps.check-new-commits.outputs.has-new-commits == 'true' }}
        run: echo "You have ${{ steps.check-new-commits.outputs.new-commits-number }} new commit(s) ✅!"
      
      - name: Print another thing if new commits couldn't be found
        if: ${{ steps.check-new-commits.outputs.has-new-commits != 'true' }}
        run: echo "You don't have new commits 🛑!"