name: Check Repo Branch for changes

on:
  workflow_call:
    inputs:
      branch:
        required: true
        type: string
    secrets:
      pat_token:
        required: true

jobs:
  
  CheckoutWorkflows:
    runs-on: ubuntu-latest
    steps:
      
      - name: Checkout eg_sfcc
        uses: actions/checkout@v3
        with:
          repository: ShopEmpowerGlobal/eg_sfcc
          ref: ${{ inputs.branch }}
          token: ${{ secrets.pat_token }}
          fetch-depth: 0
      
      - name: Detect Branch Changes
        uses: younited/detect-branch-changes-action@v0.1.3
        with:
          base_branch: ${{ inputs.branch }}
