name: EG-SFCC

# TODO: Move this to eg_SFCC once we don't need to clone TS Repo
# Update Secrets once we get final accounts from tecqsparq

on:
  workflow_dispatch:
  push:
    branches:
      - 'develop'
      - 'staging'
  pull_request:
    types: [closed] # when PR is merged, CD will be triggered

jobs:

  CheckChangesDev:
    permissions:
      id-token: write # need this for OIDC
      contents: read
    uses: ShopEmpowerGlobal/eg_workflows/.github/workflows/check_changes.yml@main
    with:
      branch: 'develop'
    secrets:
      pat_token: ${{ secrets.PAT_TOKEN }}

  # DevBuild&Deploy:
  #   permissions:
  #     id-token: write # need this for OIDC
  #     contents: read
  #   uses: ShopEmpowerGlobal/eg_workflows/.github/workflows/sfcc.yml@main
  #   with:
  #     path: 'eg_sfcc'
  #     branch: 'feature/am-6533-sfcc-deploy'
  #     hostname: 'development-na01-combsenterprise.demandware.net'
  #     username: 'berkan.cetinkaya@techsparq.com'
  #   secrets:
  #     pat_token: ${{ secrets.PAT_TOKEN }}
  #     sfcc_pass: ${{ secrets.SFCC_PASS_DEV }}