name: EG-SFDC-CORE

# TODO: Move this to eg_SFDC_core once we don't need to clone TS Repo
# Update Secrets once we get final accounts from tecqsparq

on:
  workflow_dispatch:
  push:
    branches:
      - 'develop'
      - 'staging'
  pull_request:
    types: [closed] # when PR is merged, CD will be triggered

jobs:

  Dev:
    permissions:
      id-token: write # need this for OIDC
      contents: read
    uses: ShopEmpowerGlobal/eg_workflows/.github/workflows/sfdx.yml@main
    with:
      path: 'eg_SFDC_core'
      branch: 'develop'
      username: 'artem.klimanski@techsparq.com.devartem1'
    secrets:
      pat_token: ${{ secrets.PAT_TOKEN }}
      auth_url: ${{secrets.SF_CORE_DEV_AUTH_URL}}

  Stg:
    permissions:
      id-token: write # need this for OIDC
      contents: read
    uses: ShopEmpowerGlobal/eg_workflows/.github/workflows/sfdx.yml@main
    with:
      path: 'eg_SFDC_core'
      branch: 'staging'
      username: 'artem.klimanski@techsparq.com.staging'
    secrets:
      pat_token: ${{ secrets.PAT_TOKEN }}
      auth_url: ${{secrets.SF_CORE_STG_AUTH_URL}}