name: SFCC Build Test and Deploy

on:
  workflow_call:
    inputs:
      branch:
        required: true
        type: string
      path:
        required: true
        type: string
      hostname:
        required: true
        type: string
      client_id:
        required: true
        type: string
    secrets:
      pat_token:
        required: true
      client_secret:
        required: true

jobs:
  
  Build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.21.0]

    steps:

      - name: Generate build number
        uses: einaregilsson/build-number@v3
        with:
          token: ${{secrets.pat_token}}    

      - name: Print new build number
        run: echo "Build number is $BUILD_NUMBER"

      # - name: Checkout
      #   uses: actions/checkout@v3

      - name: Checkout eg_sfcc
        uses: actions/checkout@v3
        with:
          repository: ShopEmpowerGlobal/eg_sfcc
          ref: ${{ inputs.branch }}
          token: ${{ secrets.pat_token }}
          path: ${{ inputs.path }}

      - name: Set up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install Dependencies
        run: npm install
        working-directory: ${{ inputs.path }}

      - name: 'Create env file'
        run: |
          touch .env
          echo HOSTNAME=${{ inputs.hostname }} >> .env
          echo CLIENT_ID=${{ inputs.client_id }} >> .env
          echo VERSION=${{ BUILD_NUMBER }} >> .env
          echo CLIENT_SECRET='${{ secrets.client_secret }}' >> .env
          echo ACTIVATE_CODE_VERSION='true' >> .env
          echo 
          cat .env
        working-directory: ${{ inputs.path }}

      - name: Build
        run: npm run build
        working-directory: ${{ inputs.path }}

      - name: Deploy
        run: npm run deploy
        working-directory: ${{ inputs.path }}