name: helloworld

on:
  workflow_call:
    # inputs:
    #   repository:
    #     required: true
    #     type: string
    #   ref:
    #     required: true
    #     type: string
    #   new-dev-origin:
    #     required: true
    #     type: string
    #   path:
    #     required: true
    #     type: string
    # secrets:
    #   pat_token:
    #     required: true

jobs:

  eg_sfcc:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        run: echo hello world